#!/bin/sh -e

HOME_LIXIAN=/home/ubuntu
HOME_ORIGINE_JSP=$HOME_LIXIAN/ftp_file/responsive
HOME_ORIGINE_JAVASCRIPT=$HOME_ORIGINE_JSP/javascript

HOME_ORIGINE_IMAGES=$HOME_ORIGINE_JSP/assets
HOME_ORIGINE_CLASSES=$HOME_ORIGINE_JSP/WEB-INF/classes
HOME_ORIGINE_LIB=$HOME_ORIGINE_JSP/WEB-INF/lib

HOME_DESTINATION_JSP="/var/lib/tomcat7/webapps/responsive"
HOME_DESTINATION_JAVASCRIPT=$HOME_DESTINATION_JSP/javascript

HOME_DESTINATION_IMAGES=$HOME_DESTINATION_JSP/images
HOME_DESTINATION_CLASSES=$HOME_DESTINATION_JSP/WEB-INF/classes
HOME_DESTINATION_LIB=$HOME_DESTINATION_JSP/WEB-INF/lib

echo .............. cp  $HOME_ORIGINE_JSP/*.jsp $HOME_DESTINATION_JSP
cp  $HOME_ORIGINE_JSP/*.jsp $HOME_DESTINATION_JSP

echo .............. cp -R $HOME_ORIGINE_IMAGES/* $HOME_DESTINATION_IMAGES
cp -R $HOME_ORIGINE_IMAGES/* $HOME_DESTINATION_IMAGES

echo .............. cp -R $HOME_ORIGINE_JAVASCRIPT/* $HOME_DESTINATION_JAVASCRIPT
cp  -R $HOME_ORIGINE_JAVASCRIPT/* $HOME_DESTINATION_JAVASCRIPT

echo .............. cp -R $HOME_ORIGINE_CLASSES/* $HOME_DESTINATION_CLASSES
cp -R $HOME_ORIGINE_CLASSES/* $HOME_DESTINATION_CLASSES

echo .............. cp -R $HOME_ORIGINE_LIB/* $HOME_DESTINATION_LIB
cp -R $HOME_ORIGINE_LIB/* $HOME_DESTINATION_LIB

